# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core
#https://dev.azure.com/ignatandrei1970/AOPRoslyn/
pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
 

- script: | 
    cd AOPRoslyn 
    dotnet tool restore 
- script: dotnet restore AOPRoslyn\AOPRoslyn.sln
- script: dotnet build AOPRoslyn\AOPRoslyn.sln --configuration $(buildConfiguration)
- script:  | 
    cd AOPRoslyn 
    dotnet tool run pwsh -f ./makenuget.ps1
- script: dotnet pack AOPRoslyn\aopCmd\aop.csproj  --no-build -o $(Build.ArtifactStagingDirectory) /p:Configuration=$(buildConfiguration) # --verbosity Detailed
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop1

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'nugetAndrei'

# - task: NuGetCommand@2
#   inputs:
#     command: push
#     nuGetFeedType: external
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'

- task: DotNetCoreCLI@2
  displayName: Push Nuget Package
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)/*.nupkg
      -s https://api.nuget.org/v3/index.json
      -k $(NuGetSourceServerApiKey)
